#!/usr/bin/env bash
set -e
base=$(dirname $0)
make -C $base --silent
if [ -z "$*" ] ; then
	target=song # XXX?
else
	target="$1"
	shift
fi
cc -Wall -O0 -g ${target}.c -o ${target} -L${base} -I${base} -ldfg -lm
./${target} $*
